import Link from 'next/link'
import { Brain, Zap, LineChart } from 'lucide-react'

export default function Home() {
  return (
    <div className="font-sans text-gray-900 border-t border-[#0F172A]">
      {/* Hero Section */}
      <section className="relative px-6 py-24 md:py-32 flex flex-col items-center text-center bg-gradient-to-br from-indigo-50 via-slate-50 to-violet-50 min-h-[75vh] justify-center overflow-hidden">
        
        {/* Optional background decoration */}
        <div className="absolute inset-0 z-0 opacity-40 mix-blend-multiply pointer-events-none">
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-indigo-300 rounded-full mix-blend-multiply filter blur-[120px] animate-blob"></div>
          <div className="absolute top-1/3 right-1/4 w-96 h-96 bg-violet-300 rounded-full mix-blend-multiply filter blur-[120px] animate-blob animation-delay-2000"></div>
        </div>

        <div className="relative z-10 max-w-4xl mx-auto flex flex-col items-center">
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-[#111827] mb-6 leading-tight">
            Practice Smarter. <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-500 to-violet-500">Get Hired Faster.</span>
          </h1>
          
          <p className="text-lg md:text-xl text-gray-600 max-w-2xl mb-12 font-medium leading-relaxed">
            AI-powered mock interviews tailored to your role. Get instant feedback and track your progress.
          </p>
          
          <div className="flex flex-col sm:flex-row items-center gap-4 sm:gap-6 w-full sm:w-auto">
            <Link 
              href="/signup" 
              className="w-full sm:w-auto bg-gradient-to-r from-indigo-500 to-violet-500 hover:from-indigo-600 hover:to-violet-600 text-white px-8 py-4 rounded-full font-bold text-lg transition-transform hover:scale-105 shadow-lg shadow-indigo-500/25 flex items-center justify-center"
            >
              Start Practicing &rarr;
            </Link>
            
            <Link 
              href="/login" 
              className="w-full sm:w-auto bg-transparent border-2 border-slate-300 hover:border-slate-400 hover:bg-slate-50 text-slate-700 px-8 py-4 rounded-full font-bold text-lg transition-all flex items-center justify-center"
            >
              Login
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 md:py-32 px-6 bg-white relative z-10">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 md:gap-12">
            
            {/* Card 1 */}
            <div className="bg-white p-8 rounded-2xl shadow-sm hover:shadow-md transition-shadow border border-gray-100 flex flex-col items-start group">
              <div className="w-14 h-14 bg-indigo-50 rounded-full flex items-center justify-center text-indigo-600 mb-6 group-hover:scale-110 transition-transform">
                <Brain size={28} />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-3">Smart Questions</h3>
              <p className="text-gray-500 font-medium leading-relaxed">
                Role-specific questions generated by AI for your exact position
              </p>
            </div>

            {/* Card 2 */}
            <div className="bg-white p-8 rounded-2xl shadow-sm hover:shadow-md transition-shadow border border-gray-100 flex flex-col items-start group">
              <div className="w-14 h-14 bg-violet-50 rounded-full flex items-center justify-center text-violet-600 mb-6 group-hover:scale-110 transition-transform">
                <Zap size={28} />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-3">Instant Feedback</h3>
              <p className="text-gray-500 font-medium leading-relaxed">
                Get scored and reviewed within seconds of submitting your answer
              </p>
            </div>

            {/* Card 3 */}
            <div className="bg-white p-8 rounded-2xl shadow-sm hover:shadow-md transition-shadow border border-gray-100 flex flex-col items-start group">
              <div className="w-14 h-14 bg-blue-50 rounded-full flex items-center justify-center text-indigo-500 mb-6 group-hover:scale-110 transition-transform">
                <LineChart size={28} />
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-3">Track Progress</h3>
              <p className="text-gray-500 font-medium leading-relaxed">
                All your sessions saved so you can watch yourself improve
              </p>
            </div>

          </div>
        </div>
      </section>

    </div>
  )
}