apiVersion: apps/v1
kind: Deployment
metadata:
  name: prepai-auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 22i0789/prepai-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: SECRET_KEY
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "1440"
