apiVersion: apps/v1
kind: Deployment
metadata:
  name: prepai-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 22i0789/prepai-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: DATABASE_URL
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: OPENAI_API_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: prepai-secrets
                  key: SECRET_KEY
