apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secrets.yml
- db-deployment.yml
- db-service.yml
- auth-deployment.yml
- auth-service.yml
- backend-deployment.yml
- backend-service.yml
- frontend-deployment.yml
- frontend-service.yml

images:
- name: 22i0789/prepai-auth-service
  newName: 22i0789/prepai-auth-service
  newTag: 476aefbbf3ab2a1bd72ec3e53fc4f0a4a2f5dc82
- name: 22i0789/prepai-backend
  newName: 22i0789/prepai-backend
  newTag: 476aefbbf3ab2a1bd72ec3e53fc4f0a4a2f5dc82
- name: 22i0789/prepai-frontend
  newName: 22i0789/prepai-frontend
  newTag: 476aefbbf3ab2a1bd72ec3e53fc4f0a4a2f5dc82
