apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secrets.yml
- db-deployment.yml
- db-service.yml
- auth-deployment.yml
- auth-service.yml
- backend-deployment.yml
- backend-service.yml
- frontend-deployment.yml
- frontend-service.yml

images:
- name: 22i0789/prepai-auth-service
  newName: 22i0789/prepai-auth-service
  newTag: 3e07704b4d624e2a8101495f0875f4c3f34aa44b
- name: 22i0789/prepai-backend
  newName: 22i0789/prepai-backend
  newTag: 3e07704b4d624e2a8101495f0875f4c3f34aa44b
- name: 22i0789/prepai-frontend
  newName: 22i0789/prepai-frontend
  newTag: 3e07704b4d624e2a8101495f0875f4c3f34aa44b
