apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secrets.yml
- db-deployment.yml
- db-service.yml
- auth-deployment.yml
- auth-service.yml
- backend-deployment.yml
- backend-service.yml
- frontend-deployment.yml
- frontend-service.yml

images:
- name: 22i0789/prepai-auth-service
  newName: 22i0789/prepai-auth-service
  newTag: c546f99d5235877ab1b94443374727922f6ff9d2
- name: 22i0789/prepai-backend
  newName: 22i0789/prepai-backend
  newTag: c546f99d5235877ab1b94443374727922f6ff9d2
- name: 22i0789/prepai-frontend
  newName: 22i0789/prepai-frontend
  newTag: c546f99d5235877ab1b94443374727922f6ff9d2
