apiVersion: v1
kind: Secret
metadata:
  name: prepai-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "password"
  DB_NAME: "mockinterview"
  DATABASE_URL: "postgresql://postgres:password@postgres-db:5432/mockinterview"
  SECRET_KEY: "your-secure-jwt-secret-key"
  OPENAI_API_KEY: "sk-dummy-key-replace-me"
